FROM anatolelucet/neovim:0.12-bookworm@sha256:b3727d1ca96ed9837e353adca8d19896d158abc5865b2ac6f2eb69295d96e5d6

RUN apt-get update -qq \
 && apt-get install -y -qq --no-install-recommends \
     build-essential \
     ca-certificates \
     curl \
     git \
     luarocks \
 && luarocks install luacheck \
 && rm -rf /var/lib/apt/lists/*
