FROM anatolelucet/neovim:0.12-bookworm@sha256:5b673cabca92a3ec5e759b87b0a126772f7b790535f4bc06bcb997c888fc7993

RUN apt-get update -qq \
 && apt-get install -y -qq --no-install-recommends \
     build-essential \
     ca-certificates \
     curl \
     git \
     luarocks \
 && luarocks install luacheck \
 && rm -rf /var/lib/apt/lists/*
